In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [10]:
o = pd.Series([4, 7, -6, 2, 'dsf'])
o

0      4
1      7
2     -6
3      2
4    dsf
dtype: object

In [8]:
a=np.array([2,4,50])
a

array([ 2,  4, 50])

Index Objects

In [9]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
obj = pd.Series(np.arange(3), 
                index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [12]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
index[1:]

Index(['b', 'c'], dtype='object')

In [16]:
labels = pd.Index(np.arange(3), name="BemorId")
labels

Index([0, 1, 2], dtype='int64', name='BemorId')

In [18]:
obj2 = pd.Series([15, 25, 18], index=labels, name="Yosh")
obj2

BemorId
0    15
1    25
2    18
Name: Yosh, dtype: int64

In [ ]:
# ikkalasining indexsi bittami degani

obj2.index is labels

True

In [20]:
id(obj2.index), id(labels)

(2508865286320, 2508865286320)

In [22]:
obj3 = pd.Series([15, 25, 18], 
                 index=labels, 
                 name="Yosh",
                 copy=True)
obj3

BemorId
0    15
1    25
2    18
Name: Yosh, dtype: int64

In [23]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [24]:
# DataFramelarni ustunlari ham index turida bo'ladi

frame3.columns

Index(['Ohio', 'Nevada'], dtype='object')

In [29]:
labels = pd.Index(np.arange(3), name="BemorId")

In [30]:
labels2 = labels.append(pd.Index([3,4]))
labels2

Index([0, 1, 2, 3, 4], dtype='int64')

In [34]:
# 0, 1, 2
labels1 = pd.Index(np.arange(3))
# 2, 3, 4
labels2 = pd.Index(np.arange(2,5))

In [32]:
labels1.difference(labels2)

Index([0, 1], dtype='int64')

In [33]:
labels1.union(labels2)

Index([0, 1, 2, 3, 4], dtype='int64')

In [35]:
labels1.intersection(labels2)

Index([2], dtype='int64')

In [37]:
labels2.isin([2,3])

array([ True,  True, False])

In [36]:
# "isin" --> labels2 ning qiymatlari labels1 da bor yo'qliini tekshiradi

labels2.isin(labels1)

array([ True, False, False])

In [39]:
labels2.is_unique

True

In [41]:
labels2.unique()

Index([2, 3, 4], dtype='int64')

In [42]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],
                index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [43]:
# indexni o'zgartirish

obj2 =obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [44]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [45]:
obj3.reindex(np.arange(6), method="ffill")
obj3

0      blue
2    purple
4    yellow
dtype: object

In [47]:
obj3.reindex(np.arange(6))


0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [48]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [55]:
frame = pd.DataFrame(np.arange(9).reshape((3 ,3)), 
                     index=["a", "c", "d"],
                     columns=["California", "Ohio", "Texas"])
frame

California  Ohio  Texas
a           0     1      2
c           3     4      5
d           6     7      8

In [51]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [52]:
frame2 = frame.reindex(index=["a", "b", "c", "d"], method="ffill")
frame2

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [53]:
states = ["Texas", "Utah", "California"]
frame4 = frame.reindex(columns=states)
frame4

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [58]:
states = ["California", "Texas", "Utah"]
frame4 = frame.reindex(columns=states, method="ffill")
frame4

California  Texas  Utah
a           0      2     2
c           3      5     5
d           6      8     8

In [59]:
frame4.loc['a']

California    0
Texas         2
Utah          2
Name: a, dtype: int64

In [62]:
frame4.iloc[1]

California    3
Texas         5
Utah          5
Name: c, dtype: int64