In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
o = pd.Series([4, 7, -6, 2, 'dsf'])
o

0      4
1      7
2     -6
3      2
4    dsf
dtype: object

In [8]:
a=np.array([2,4,50])
a

array([ 2,  4, 50])

## Index Objects

In [9]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
obj = pd.Series(np.arange(3), 
                index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [12]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [13]:
index[1:]

Index(['b', 'c'], dtype='object')

In [16]:
labels = pd.Index(np.arange(3), name="BemorId")
labels

Index([0, 1, 2], dtype='int64', name='BemorId')

In [18]:
obj2 = pd.Series([15, 25, 18], index=labels, name="Yosh")
obj2

BemorId
0    15
1    25
2    18
Name: Yosh, dtype: int64

In [ ]:
# ikkalasining indexsi bittami degani

obj2.index is labels

True

In [20]:
id(obj2.index), id(labels)

(2508865286320, 2508865286320)

In [22]:
obj3 = pd.Series([15, 25, 18], 
                 index=labels, 
                 name="Yosh",
                 copy=True)
obj3

BemorId
0    15
1    25
2    18
Name: Yosh, dtype: int64

In [23]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [24]:
# DataFramelarni ustunlari ham index turida bo'ladi

frame3.columns

Index(['Ohio', 'Nevada'], dtype='object')

In [46]:
labels = pd.Index(np.arange(3), name="BemorId")

In [47]:
labels2 = labels.append(pd.Index([3,4]))
labels2

Index([0, 1, 2, 3, 4], dtype='int64')

In [49]:
labels

Index([0, 1, 2], dtype='int64', name='BemorId')

In [34]:
# 0, 1, 2
labels1 = pd.Index(np.arange(3))
# 2, 3, 4
labels2 = pd.Index(np.arange(2,5))

In [32]:
labels1.difference(labels2)

Index([0, 1], dtype='int64')

In [33]:
labels1.union(labels2)

Index([0, 1, 2, 3, 4], dtype='int64')

In [35]:
labels1.intersection(labels2)

Index([2], dtype='int64')

In [37]:
labels2.isin([2,3])

array([ True,  True, False])

In [36]:
# "isin" --> labels2 ning qiymatlari labels1 da bor yo'qliini tekshiradi

labels2.isin(labels1)

array([ True, False, False])

In [39]:
labels2.is_unique

True

In [41]:
labels2.unique()

Index([2, 3, 4], dtype='int64')

In [42]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6],
                index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [43]:
# indexni o'zgartirish

obj2 =obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [44]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [45]:
obj3.reindex(np.arange(6), method="ffill")
obj3

0      blue
2    purple
4    yellow
dtype: object

In [47]:
obj3.reindex(np.arange(6))


0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [48]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [55]:
frame = pd.DataFrame(np.arange(9).reshape((3 ,3)), 
                     index=["a", "c", "d"],
                     columns=["California", "Ohio", "Texas"])
frame

California  Ohio  Texas
a           0     1      2
c           3     4      5
d           6     7      8

In [51]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [52]:
frame2 = frame.reindex(index=["a", "b", "c", "d"], method="ffill")
frame2

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [53]:
states = ["Texas", "Utah", "California"]
frame4 = frame.reindex(columns=states)
frame4

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [58]:
states = ["California", "Texas", "Utah"]
frame4 = frame.reindex(columns=states, method="ffill")
frame4

California  Texas  Utah
a           0      2     2
c           3      5     5
d           6      8     8

In [59]:
frame4.loc['a']

California    0
Texas         2
Utah          2
Name: a, dtype: int64

In [62]:
frame4.iloc[1]

California    3
Texas         5
Utah          5
Name: c, dtype: int64

## Dropping Entries from an Axis

In [3]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [4]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [5]:
new_obj = obj.drop(["c", "d"])
new_obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [ ]:
#Bunda a ning o'ziga ta'sir qilmaydi, Bu shunchaki o'zgartiradi 

a = [4, 9, -3, 5, 37]
sorted(a)

[-3, 4, 5, 9, 37]

In [8]:
a

[-3, 4, 5, 9, 37]

In [ ]:
# Bunda a ning o'ziga ta'sir qiladi, Bu ich - ichiga tasir qiladi
a.sort()

In [11]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
            index=["Ohio", "Colorado", "Utah", "New York"],
            columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
new_data = data.drop(index=['Colorado', 'Ohio'])
new_data

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [16]:
new_data = data.drop(columns=[ 'one'])
new_data

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [17]:
new_data = data.drop('two', axis=1)
new_data

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [18]:
new_data = data.drop('two', axis='columns')
new_data

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [19]:
new_data = data.drop('Utah', axis=0)
new_data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [20]:
new_data = data.drop('Utah', axis='index')
new_data    

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

## Indexing, Selection, and Filtering

In [21]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [22]:
obj['b']

np.float64(1.0)

In [23]:
obj[1]

C:\Users\muxitdinov_h\AppData\Local\Temp\ipykernel_5416\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [24]:
obj[['a', 'c']]

a    0.0
c    2.0
dtype: float64

In [25]:
obj[obj.index[1:3]]

b    1.0
c    2.0
dtype: float64

In [26]:
obj.index[1:3]

Index(['b', 'c'], dtype='object')

In [27]:
obj.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [28]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [33]:
obj.loc["b", "a", "d"]

IndexingError: Too many indexers

In [29]:
obj.iloc[0:2]

a    0.0
b    1.0
dtype: float64

In [31]:
obj.loc["b": "c"] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [34]:
obj1 = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj1

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [35]:
obj1.loc["c":"a"]

Series([], dtype: float64)

In [78]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
            index=["Ohio", "Colorado", "Utah", "New York"],
            columns=["one", "two", "three", "four"])
data    

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [37]:
data['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int64

In [41]:
data1 = data[['one', 'three']]
data1

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [42]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [43]:
data['three']>5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [44]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [58]:

chdat = {
    'Ism': ['Ali', 'Vali', 'Sami'],
    'Yosh': [25, 30, 22],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro']
}

df = pd.DataFrame(chdat)

# 'Ism' ustunini indeks sifatida belgilash
df.set_index('Ism', inplace=True)

print(df)


      Yosh     Shahar
Ism                  
Ali     25   Toshkent
Vali    30  Samarqand
Sami    22     Buxoro


In [59]:
# Yangi indekslar
new_index = ['a', 'b', 'c']

# Indeksni o'zgartirish
df.index = new_index

print(df)


   Yosh     Shahar
a    25   Toshkent
b    30  Samarqand
c    22     Buxoro


## Selection on DataFrame with loc and iloc

In [79]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [81]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [82]:
data.loc[["Colorado", "Utah"]]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [83]:
data.loc[["Colorado"], ['two', 'three']]

two  three
Colorado    5      6

In [84]:
data.iloc[[0 ,2], [1, 3]]

two  four
Ohio    1     3
Utah    9    11

In [86]:
data.iloc[:, :3][data.three>5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [87]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# "at" bitta qiymatni olishga yordam beraedi

data.at['Utah', 'three']

np.int64(10)

In [90]:
data.at['Utah', 'three'] = 15
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     15    11
New York   12   13     14    15

In [ ]:
# at ning index bo'yicha ishlashi

data.iat[0,1]=100
data

one  two  three  four
Ohio        0  100      2     3
Colorado    4    5      6     7
Utah        8    9     15    11
New York   12   13     14    15

### Integer indexing pitfalls

In [93]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [94]:
ser[1]

np.float64(1.0)

In [98]:
ser1 = pd.Series(np.arange(5.), index=["b", "e", "a", "c", "d"])
ser1

b    0.0
e    1.0
a    2.0
c    3.0
d    4.0
dtype: float64

In [99]:
ser1[::-1]

d    4.0
c    3.0
a    2.0
e    1.0
b    0.0
dtype: float64

In [100]:
data

one  two  three  four
Ohio        0  100      2     3
Colorado    4    5      6     7
Utah        8    9     15    11
New York   12   13     14    15

In [102]:
data.loc[:, "one"] = 1
data

one  two  three  four
Ohio        1  100      2     3
Colorado    1    5      6     7
Utah        1    9     15    11
New York    1   13     14    15

In [104]:
data.iloc[2] = 5
data

one  two  three  four
Ohio        1  100      2     3
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [106]:
data.loc[data["four"] > 5] = 3
data

one  two  three  four
Ohio        1  100      2     3
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [107]:
data.loc[data.three == 5, "three"] = 6
data

one  two  three  four
Ohio        1  100      2     3
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

## Arithmetic and Data Alignment

In [3]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], 
                index=["a", "c", "d", "e"])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
                index=["a", "c", "e", "f", "g"])

In [4]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [6]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [7]:
s1 * s2

a   -15.33
c    -9.00
d      NaN
e    -2.25
f      NaN
g      NaN
dtype: float64

In [8]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                    columns=list("bcd"),
                    index=["Ohio", "Texas", "Colorado"])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [9]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list("bde"),
                    index=["Utah", "Ohio", "Texas", "Oregon"])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [10]:
df1 + df2 

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [11]:
df1 * df2

b   c     d   e
Colorado   NaN NaN   NaN NaN
Ohio       0.0 NaN   8.0 NaN
Oregon     NaN NaN   NaN NaN
Texas     18.0 NaN  35.0 NaN
Utah       NaN NaN   NaN NaN

In [14]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})
print(df1)
print(df2)

   A
0  1
1  2
   B
0  3
1  4


In [13]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

## Arithmetic methods with fill values

In [16]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                    columns=list("abcd"))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                    columns=list("abcde"))

In [17]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [18]:
df2.loc[1, "b"] = np.nan

In [19]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [20]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [23]:
# NaN larning o'rniga biror qiymat bilan to'ldirish

df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [25]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

## Operations between DataFrame and Series

In [27]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [28]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [29]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                      columns=list("bde"),
                      index=["Utah", "Ohio", "Texas", "Oregon"])

series = frame.iloc[0]

In [30]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [31]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [32]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [33]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [34]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [35]:
series3 = frame["d"]
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [ ]:
# fram-series3

frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

In [37]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                      columns=list("bde"),
                      index=["Utah", "Ohio", "Texas", "Oregon"])

frame

b         d         e
Utah   -0.047423 -1.357523 -0.977036
Ohio    0.194445 -0.068383 -0.736298
Texas  -0.612631  1.323485 -1.024945
Oregon -1.189012 -0.896244 -1.352296

In [38]:
np.abs(frame)

b         d         e
Utah    0.047423  1.357523  0.977036
Ohio    0.194445  0.068383  0.736298
Texas   0.612631  1.323485  1.024945
Oregon  1.189012  0.896244  1.352296

In [39]:
def f1(x):
    return x.max() - x.min()
frame.apply(f1)

b    1.383457
d    2.681008
e    0.615998
dtype: float64

In [40]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)

b         d         e
min -1.189012 -1.357523 -1.352296
max  0.194445  1.323485 -0.736298

In [ ]:
# 2 ta xonagacha yaxlitlab chiqarish

def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

b      d      e
Utah    -0.05  -1.36  -0.98
Ohio     0.19  -0.07  -0.74
Texas   -0.61   1.32  -1.02
Oregon  -1.19  -0.90  -1.35

## Sorting and Ranking

In [44]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [45]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [46]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                      index=["three", "one"],
                      columns=["d", "a", "b", "c"])

frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [47]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
# ascending Teskari yoki To'g'ri tartilash

frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [50]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [53]:
frame.sort_values(by='b', ascending=False)

b  a
1  7  1
0  4  0
3  2  1
2 -3  0

In [55]:
# Birinchi qaysi valueslarni tartiblashini bilib olish

frame.sort_values(['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [56]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

## Axis Indexes with Duplicate Labels

In [57]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [59]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                   index=["a", "a", "b", "b", "c"])

df

0         1         2
a  0.330772 -0.910541 -0.164400
a -0.130925  0.513265  0.924663
b -0.097280  0.827953 -0.650170
b -2.338491 -0.028162 -0.188078
c  2.135061 -0.324691 -0.085340

In [60]:
df.loc['b']

0         1         2
b -0.097280  0.827953 -0.650170
b -2.338491 -0.028162 -0.188078

In [61]:
df.loc['b', 0]

b   -0.097280
b   -2.338491
Name: 0, dtype: float64